services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  dynamodb-init:
    image: amazon/aws-cli
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-2
    volumes:
      - ./init_local_database.sh:/init_local_database.sh
    entrypoint: ["/bin/sh", "/init_local_database.sh"]

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=ap-northeast-2
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  sqs-init:
    image: amazon/aws-cli
    depends_on:
      - localstack
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-2
    volumes:
      - ./init_local_sqs.sh:/init_local_sqs.sh
    entrypoint: ["/bin/sh", "/init_local_sqs.sh"]