name: eventworker_workflow.yml
on:
  push:
    branches: [ "eventworker" ]

jobs:
  build:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Build event worker binary
        run: |
          make build-eventworker

  deploy:
    name: Deploy to lambda
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Deploy to lambda
        env:
          EVENTWORKER_LAMBDA_FUNCTION_NAME: ${{ secrets.EVENTWORKER_LAMBDA_FUNCTION_NAME }}
        run: |
          make deploy-eventworker